# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - ./lib/rubocop/cops/no_execute_in_migrations.rb
  - ./lib/rubocop/cops/only_atomic_migrations.rb

AllCops:
  Exclude:
    - 'Gemfile.lock'

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Cops/NoExecuteInMigrations:
  Enabled: true

Cops/OnlyAtomicMigrations:
  Enabled: false
