secret_key_base: secret_key
auth:
  github:
    client_id: gh_client_id
    secret: gh_secret_key
  google:
    client_id: google_client_id
    secret: google_secret
stripe:
  private_key: sk_test
  public_key: pk_test
  webhook_receive_test_events: true
  signing_secret:
    - whsec
